services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai_web_app
          property: connectionString

databases:
  - name: ai_web_app
    databaseName: ai_web_app
    user: ai_web_app_user
